#!/bin/bash

# Check for empty folder name
if [ -z "$1" ] || [ -z "$2" ] || [ -z "$3" ]; then
  exit "Unknown folder name or crop length or sample width: $1 + $2 + $3"
fi

# Merge MP3 files
if [ ! -f "$1/$(basename $1)_merged.mp3" ]; then
  cat $1/*.mp3 > "$1/$(basename $1)_merged.mp3"
fi

# Cut the file into desired length
if [ ! -f "$1/$(basename $1)_merged_$2.mp3" ]; then
  ffmpeg -t $2 -i "$1/$(basename $1)_merged.mp3" -acodec copy "$1/$(basename $1)_merged_$2.mp3"
fi

# Convert to wav
if [ ! -f "$1/$(basename $1)_merged_$2.wav" ]; then
  ffmpeg -i $1/$(basename $1)_merged_$2.mp3 -acodec pcm_s16le -ac 1 -ar 8000 "$1/$(basename $1)_merged_$2.wav"
fi

# Remove silence
#sox $1/$(basename $1)_merged_$2.wav $1/$(basename $1)_merged_$2_silent.wav silence -l 1 0.1 1% -1 0.8 1%
ffmpeg -i $1/$(basename $1)_merged_$2.wav -af silenceremove=1:0:0:-1:1:-30dB $1/$(basename $1)_merged_$2_silent.wav

if [ ! -d $1/split/$3/wav ]; then
  mkdir -p $1/split/$3/wav
fi

# Split the file
files=$(ls -1 $1/split/$3/wav | wc -l)
if [ ! $files -gt 0 ]; then
  ffmpeg -i $1/$(basename $1)_merged_$2_silent.wav -f segment -segment_time $3 -c copy $1/split/$3/wav/%03d.wav
fi

if [ ! "$4" == "s" ]; then
  exit 0
fi

if [ ! -d $1/split/$3/spect ]; then
  mkdir -p $1/split/$3/spect
fi

# Create spectrogram
for file in $1/split/$3/wav/*.wav; do
  ffmpeg -i $file -lavfi showspectrumpic=s=960x540:saturation=1:gain=5:legend=0:win_func=poisson:scale=lin $1/split/$3/spect/$(basename $file).png
  #ffmpeg -i $file -lavfi showspectrumpic=gain=1 $1/split/$3/spect/$(basename $file).png
  #sox $file -n spectrogram -r -o $1/split/$3/spect/$(basename $file).png
done

