#!/bin/bash

# Check for empty folder name
if [ -z "$1" ] || [ -z "$2" ] || [ -z "$3" ]; then
  exit "Unknown folder name or crop length or sample width: $1 + $2 + $3"
fi

if [ ! -f "$1/$(basename $1)_merged.mp3" ]; then
  cat $1/*.mp3 > "$1/$(basename $1)_merged.mp3"
fi

# Convert to wav
if [ ! -f "$1/$(basename $1).wav" ]; then
  ffmpeg -i $1/$(basename $1)_merged.mp3 -acodec pcm_s16le -t 512 -ac 1 -ar 16000 "$1/$(basename $1).wav"
fi

# Remove silence
if [ ! -f "$1/$(basename $1)_silent.wav" ]; then
  ffmpeg -i $1/$(basename $1).wav -af silenceremove=1:0:0:-1:1:-30dB $1/$(basename $1)_silent.wav
fi

if [ ! -d $1/split/$3/wav ]; then
  mkdir -p $1/split/$3/wav
fi

# Split the file
files=$(ls -1 $1/split/$3/wav | wc -l)
if [ ! $files -gt 0 ]; then
  ffmpeg -i $1/$(basename $1)_silent.wav -t $2 -ss 20 -f segment -segment_time $3 -c copy $1/split/$3/wav/%03d.wav
fi

if [ ! "$4" == "s" ]; then
  exit 0
fi

if [ ! -d $1/split/$3/spect ]; then
  mkdir -p $1/split/$3/spect
fi

# Create spectrogram
generate_spect () {
  ffmpeg -i $1 -lavfi showspectrumpic=s=960x540:saturation=1:gain=5:legend=0:win_func=poisson:scale=lin $2/split/$3/spect/$(basename $1).png
}

export -f generate_spect
find  $1/split/$3/wav/ -maxdepth 1 -mindepth 1 -type f | parallel generate_spect {} $1 $3

